### PR TITLE
Updated Video.js to 5.0

### PR DESCRIPTION
**Pull request by gilest**
Hi there, thanks for putting this together.

Had a go at updating compatibility for the new release of Video.js.

A couple of notes:
- Also included is `grunt-contrib-connect` for use as a development server. It's in a separate commit so that I can yank it out if you please.
- Didn't see any 'controls' key in the options, so I left out the conditional for it.
- I found the text indentation to be a bit confusing, sorry if I messed it up.

References I used:
- [Video.js 5.0 Changes](https://github.com/videojs/video.js/wiki/5.0-Change-Details)
- [Update of video-js-youtube tech](https://github.com/eXon/videojs-youtube/commit/8d8d37c9f9eeecc426c7188c1e7754540fac06bf)

### CODE REVIEW

**Comment by featheast** [comment]
Hi gilest, thanks for your pull request, and sorry for the late reply. It's really good to have support for the VJS 5.0 version! My concern is, however, VJS5.0 is still in it's early stage of life cycle, which means a lot of third party plugins haven't updated so far. So instead of merging your code into master, it would be actually better to have a separate branch dedicated for VJS 5.0 version until things getting more stable?

**Comment by gilest** [comment]
Hi featheast. I totally agree! Didn't really think before targeting master. I don't think it's possible to edit this PR to target a different branch. So should I close it and open another?

**Comment by jbroberg** [comment]
Hi gilest

Thanks also for your contribution. I checked your branch out and tried it myself - great stuff.

I have made a new branch called 'vjs5' which you can target. A couple of other suggestions if you are interested in updating the pull req:
- You might as well bump bower dependencies for shaka (to 1.6) and videojs (to 5.2.2) to latest
- Due to how controlbar elements are now handled the quality picker is now last, and renders outside the player. I think we'd like to keep it in the player window if possible.
  screen shot 2015-11-24 at 8 57 55 am
- There is the following warning on the console:

> VIDEOJS: WARN: The Shaka tech was registered as a component. It should instead be registered 
> using videojs.registerTech(name, tech)

**Comment by gilest** [comment]
See new PR #6 for updated changes.

**Pull request closed without merging**
